#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : google-auth
Version  : 1.6.3
Release  : 5
URL      : https://files.pythonhosted.org/packages/ef/77/eb1d3288dbe2ba6f4fe50b9bb41770bac514cd2eb91466b56d44a99e2f8d/google-auth-1.6.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ef/77/eb1d3288dbe2ba6f4fe50b9bb41770bac514cd2eb91466b56d44a99e2f8d/google-auth-1.6.3.tar.gz
Summary  : Google Authentication Library
Group    : Development/Tools
License  : Apache-2.0
Requires: google-auth-license = %{version}-%{release}
Requires: google-auth-python = %{version}-%{release}
Requires: google-auth-python3 = %{version}-%{release}
Requires: cachetools
Requires: pyasn1-modules
Requires: rsa
Requires: six
BuildRequires : buildreq-distutils3

%description
==========================
        
        |build| |docs| |pypi|
        
        This library simplifies using Google's various server-to-server authentication
        mechanisms to access Google APIs.

%package license
Summary: license components for the google-auth package.
Group: Default

%description license
license components for the google-auth package.


%package python
Summary: python components for the google-auth package.
Group: Default
Requires: google-auth-python3 = %{version}-%{release}

%description python
python components for the google-auth package.


%package python3
Summary: python3 components for the google-auth package.
Group: Default
Requires: python3-core

%description python3
python3 components for the google-auth package.


%prep
%setup -q -n google-auth-1.6.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550701963
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/google-auth
cp LICENSE %{buildroot}/usr/share/package-licenses/google-auth/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/google-auth/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
